import { useState, useEffect } from 'react'

export type Country = {
  name: string
  flag_url: string
  phone_code: string
  code: string
}

// Complete list of countries with their phone codes and flag URLs
const allCountries: Country[] = [
  { name: 'Afganistán', code: 'af', flag_url: 'https://flagcdn.com/w40/af.png', phone_code: '+93' },
  { name: 'Albania', code: 'al', flag_url: 'https://flagcdn.com/w40/al.png', phone_code: '+355' },
  { name: 'Alemania', code: 'de', flag_url: 'https://flagcdn.com/w40/de.png', phone_code: '+49' },
  { name: 'Andorra', code: 'ad', flag_url: 'https://flagcdn.com/w40/ad.png', phone_code: '+376' },
  { name: 'Angola', code: 'ao', flag_url: 'https://flagcdn.com/w40/ao.png', phone_code: '+244' },
  { name: 'Argentina', code: 'ar', flag_url: 'https://flagcdn.com/w40/ar.png', phone_code: '+54' },
  { name: 'Armenia', code: 'am', flag_url: 'https://flagcdn.com/w40/am.png', phone_code: '+374' },
  { name: 'Australia', code: 'au', flag_url: 'https://flagcdn.com/w40/au.png', phone_code: '+61' },
  { name: 'Austria', code: 'at', flag_url: 'https://flagcdn.com/w40/at.png', phone_code: '+43' },
  { name: 'Azerbaiyán', code: 'az', flag_url: 'https://flagcdn.com/w40/az.png', phone_code: '+994' },
  { name: 'Bahamas', code: 'bs', flag_url: 'https://flagcdn.com/w40/bs.png', phone_code: '+1242' },
  { name: 'Bangladés', code: 'bd', flag_url: 'https://flagcdn.com/w40/bd.png', phone_code: '+880' },
  { name: 'Barbados', code: 'bb', flag_url: 'https://flagcdn.com/w40/bb.png', phone_code: '+1246' },
  { name: 'Baréin', code: 'bh', flag_url: 'https://flagcdn.com/w40/bh.png', phone_code: '+973' },
  { name: 'Bélgica', code: 'be', flag_url: 'https://flagcdn.com/w40/be.png', phone_code: '+32' },
  { name: 'Belice', code: 'bz', flag_url: 'https://flagcdn.com/w40/bz.png', phone_code: '+501' },
  { name: 'Benín', code: 'bj', flag_url: 'https://flagcdn.com/w40/bj.png', phone_code: '+229' },
  { name: 'Bielorrusia', code: 'by', flag_url: 'https://flagcdn.com/w40/by.png', phone_code: '+375' },
  { name: 'Bolivia', code: 'bo', flag_url: 'https://flagcdn.com/w40/bo.png', phone_code: '+591' },
  { name: 'Bosnia y Herzegovina', code: 'ba', flag_url: 'https://flagcdn.com/w40/ba.png', phone_code: '+387' },
  { name: 'Botsuana', code: 'bw', flag_url: 'https://flagcdn.com/w40/bw.png', phone_code: '+267' },
  { name: 'Brasil', code: 'br', flag_url: 'https://flagcdn.com/w40/br.png', phone_code: '+55' },
  { name: 'Brunéi', code: 'bn', flag_url: 'https://flagcdn.com/w40/bn.png', phone_code: '+673' },
  { name: 'Bulgaria', code: 'bg', flag_url: 'https://flagcdn.com/w40/bg.png', phone_code: '+359' },
  { name: 'Burkina Faso', code: 'bf', flag_url: 'https://flagcdn.com/w40/bf.png', phone_code: '+226' },
  { name: 'Burundi', code: 'bi', flag_url: 'https://flagcdn.com/w40/bi.png', phone_code: '+257' },
  { name: 'Bután', code: 'bt', flag_url: 'https://flagcdn.com/w40/bt.png', phone_code: '+975' },
  { name: 'Cabo Verde', code: 'cv', flag_url: 'https://flagcdn.com/w40/cv.png', phone_code: '+238' },
  { name: 'Camboya', code: 'kh', flag_url: 'https://flagcdn.com/w40/kh.png', phone_code: '+855' },
  { name: 'Camerún', code: 'cm', flag_url: 'https://flagcdn.com/w40/cm.png', phone_code: '+237' },
  { name: 'Canadá', code: 'ca', flag_url: 'https://flagcdn.com/w40/ca.png', phone_code: '+1' },
  { name: 'Catar', code: 'qa', flag_url: 'https://flagcdn.com/w40/qa.png', phone_code: '+974' },
  { name: 'Chad', code: 'td', flag_url: 'https://flagcdn.com/w40/td.png', phone_code: '+235' },
  { name: 'Chile', code: 'cl', flag_url: 'https://flagcdn.com/w40/cl.png', phone_code: '+56' },
  { name: 'China', code: 'cn', flag_url: 'https://flagcdn.com/w40/cn.png', phone_code: '+86' },
  { name: 'Chipre', code: 'cy', flag_url: 'https://flagcdn.com/w40/cy.png', phone_code: '+357' },
  { name: 'Colombia', code: 'co', flag_url: 'https://flagcdn.com/w40/co.png', phone_code: '+57' },
  { name: 'Comoras', code: 'km', flag_url: 'https://flagcdn.com/w40/km.png', phone_code: '+269' },
  { name: 'Congo', code: 'cg', flag_url: 'https://flagcdn.com/w40/cg.png', phone_code: '+242' },
  { name: 'Corea del Norte', code: 'kp', flag_url: 'https://flagcdn.com/w40/kp.png', phone_code: '+850' },
  { name: 'Corea del Sur', code: 'kr', flag_url: 'https://flagcdn.com/w40/kr.png', phone_code: '+82' },
  { name: 'Costa de Marfil', code: 'ci', flag_url: 'https://flagcdn.com/w40/ci.png', phone_code: '+225' },
  { name: 'Costa Rica', code: 'cr', flag_url: 'https://flagcdn.com/w40/cr.png', phone_code: '+506' },
  { name: 'Croacia', code: 'hr', flag_url: 'https://flagcdn.com/w40/hr.png', phone_code: '+385' },
  { name: 'Cuba', code: 'cu', flag_url: 'https://flagcdn.com/w40/cu.png', phone_code: '+53' },
  { name: 'Dinamarca', code: 'dk', flag_url: 'https://flagcdn.com/w40/dk.png', phone_code: '+45' },
  { name: 'Dominica', code: 'dm', flag_url: 'https://flagcdn.com/w40/dm.png', phone_code: '+1767' },
  { name: 'Ecuador', code: 'ec', flag_url: 'https://flagcdn.com/w40/ec.png', phone_code: '+593' },
  { name: 'Egipto', code: 'eg', flag_url: 'https://flagcdn.com/w40/eg.png', phone_code: '+20' },
  { name: 'El Salvador', code: 'sv', flag_url: 'https://flagcdn.com/w40/sv.png', phone_code: '+503' },
  { name: 'Emiratos Árabes Unidos', code: 'ae', flag_url: 'https://flagcdn.com/w40/ae.png', phone_code: '+971' },
  { name: 'Eritrea', code: 'er', flag_url: 'https://flagcdn.com/w40/er.png', phone_code: '+291' },
  { name: 'Eslovaquia', code: 'sk', flag_url: 'https://flagcdn.com/w40/sk.png', phone_code: '+421' },
  { name: 'Eslovenia', code: 'si', flag_url: 'https://flagcdn.com/w40/si.png', phone_code: '+386' },
  { name: 'España', code: 'es', flag_url: 'https://flagcdn.com/w40/es.png', phone_code: '+34' },
  { name: 'Estados Unidos', code: 'us', flag_url: 'https://flagcdn.com/w40/us.png', phone_code: '+1' },
  { name: 'Estonia', code: 'ee', flag_url: 'https://flagcdn.com/w40/ee.png', phone_code: '+372' },
  { name: 'Etiopía', code: 'et', flag_url: 'https://flagcdn.com/w40/et.png', phone_code: '+251' },
  { name: 'Filipinas', code: 'ph', flag_url: 'https://flagcdn.com/w40/ph.png', phone_code: '+63' },
  { name: 'Finlandia', code: 'fi', flag_url: 'https://flagcdn.com/w40/fi.png', phone_code: '+358' },
  { name: 'Fiyi', code: 'fj', flag_url: 'https://flagcdn.com/w40/fj.png', phone_code: '+679' },
  { name: 'Francia', code: 'fr', flag_url: 'https://flagcdn.com/w40/fr.png', phone_code: '+33' },
  { name: 'Gabón', code: 'ga', flag_url: 'https://flagcdn.com/w40/ga.png', phone_code: '+241' },
  { name: 'Gambia', code: 'gm', flag_url: 'https://flagcdn.com/w40/gm.png', phone_code: '+220' },
  { name: 'Georgia', code: 'ge', flag_url: 'https://flagcdn.com/w40/ge.png', phone_code: '+995' },
  { name: 'Ghana', code: 'gh', flag_url: 'https://flagcdn.com/w40/gh.png', phone_code: '+233' },
  { name: 'Granada', code: 'gd', flag_url: 'https://flagcdn.com/w40/gd.png', phone_code: '+1473' },
  { name: 'Grecia', code: 'gr', flag_url: 'https://flagcdn.com/w40/gr.png', phone_code: '+30' },
  { name: 'Guatemala', code: 'gt', flag_url: 'https://flagcdn.com/w40/gt.png', phone_code: '+502' },
  { name: 'Guinea', code: 'gn', flag_url: 'https://flagcdn.com/w40/gn.png', phone_code: '+224' },
  { name: 'Guinea-Bisáu', code: 'gw', flag_url: 'https://flagcdn.com/w40/gw.png', phone_code: '+245' },
  { name: 'Guinea Ecuatorial', code: 'gq', flag_url: 'https://flagcdn.com/w40/gq.png', phone_code: '+240' },
  { name: 'Guyana', code: 'gy', flag_url: 'https://flagcdn.com/w40/gy.png', phone_code: '+592' },
  { name: 'Haití', code: 'ht', flag_url: 'https://flagcdn.com/w40/ht.png', phone_code: '+509' },
  { name: 'Honduras', code: 'hn', flag_url: 'https://flagcdn.com/w40/hn.png', phone_code: '+504' },
  { name: 'Hungría', code: 'hu', flag_url: 'https://flagcdn.com/w40/hu.png', phone_code: '+36' },
  { name: 'India', code: 'in', flag_url: 'https://flagcdn.com/w40/in.png', phone_code: '+91' },
  { name: 'Indonesia', code: 'id', flag_url: 'https://flagcdn.com/w40/id.png', phone_code: '+62' },
  { name: 'Irak', code: 'iq', flag_url: 'https://flagcdn.com/w40/iq.png', phone_code: '+964' },
  { name: 'Irán', code: 'ir', flag_url: 'https://flagcdn.com/w40/ir.png', phone_code: '+98' },
  { name: 'Irlanda', code: 'ie', flag_url: 'https://flagcdn.com/w40/ie.png', phone_code: '+353' },
  { name: 'Islandia', code: 'is', flag_url: 'https://flagcdn.com/w40/is.png', phone_code: '+354' },
  { name: 'Israel', code: 'il', flag_url: 'https://flagcdn.com/w40/il.png', phone_code: '+972' },
  { name: 'Italia', code: 'it', flag_url: 'https://flagcdn.com/w40/it.png', phone_code: '+39' },
  { name: 'Jamaica', code: 'jm', flag_url: 'https://flagcdn.com/w40/jm.png', phone_code: '+1876' },
  { name: 'Japón', code: 'jp', flag_url: 'https://flagcdn.com/w40/jp.png', phone_code: '+81' },
  { name: 'Jordania', code: 'jo', flag_url: 'https://flagcdn.com/w40/jo.png', phone_code: '+962' },
  { name: 'Kazajistán', code: 'kz', flag_url: 'https://flagcdn.com/w40/kz.png', phone_code: '+7' },
  { name: 'Kenia', code: 'ke', flag_url: 'https://flagcdn.com/w40/ke.png', phone_code: '+254' },
  { name: 'Kirguistán', code: 'kg', flag_url: 'https://flagcdn.com/w40/kg.png', phone_code: '+996' },
  { name: 'Kiribati', code: 'ki', flag_url: 'https://flagcdn.com/w40/ki.png', phone_code: '+686' },
  { name: 'Kuwait', code: 'kw', flag_url: 'https://flagcdn.com/w40/kw.png', phone_code: '+965' },
  { name: 'Laos', code: 'la', flag_url: 'https://flagcdn.com/w40/la.png', phone_code: '+856' },
  { name: 'Lesoto', code: 'ls', flag_url: 'https://flagcdn.com/w40/ls.png', phone_code: '+266' },
  { name: 'Letonia', code: 'lv', flag_url: 'https://flagcdn.com/w40/lv.png', phone_code: '+371' },
  { name: 'Líbano', code: 'lb', flag_url: 'https://flagcdn.com/w40/lb.png', phone_code: '+961' },
  { name: 'Liberia', code: 'lr', flag_url: 'https://flagcdn.com/w40/lr.png', phone_code: '+231' },
  { name: 'Libia', code: 'ly', flag_url: 'https://flagcdn.com/w40/ly.png', phone_code: '+218' },
  { name: 'Liechtenstein', code: 'li', flag_url: 'https://flagcdn.com/w40/li.png', phone_code: '+423' },
  { name: 'Lituania', code: 'lt', flag_url: 'https://flagcdn.com/w40/lt.png', phone_code: '+370' },
  { name: 'Luxemburgo', code: 'lu', flag_url: 'https://flagcdn.com/w40/lu.png', phone_code: '+352' },
  { name: 'Madagascar', code: 'mg', flag_url: 'https://flagcdn.com/w40/mg.png', phone_code: '+261' },
  { name: 'Malasia', code: 'my', flag_url: 'https://flagcdn.com/w40/my.png', phone_code: '+60' },
  { name: 'Malaui', code: 'mw', flag_url: 'https://flagcdn.com/w40/mw.png', phone_code: '+265' },
  { name: 'Maldivas', code: 'mv', flag_url: 'https://flagcdn.com/w40/mv.png', phone_code: '+960' },
  { name: 'Malí', code: 'ml', flag_url: 'https://flagcdn.com/w40/ml.png', phone_code: '+223' },
  { name: 'Malta', code: 'mt', flag_url: 'https://flagcdn.com/w40/mt.png', phone_code: '+356' },
  { name: 'Marruecos', code: 'ma', flag_url: 'https://flagcdn.com/w40/ma.png', phone_code: '+212' },
  { name: 'Mauricio', code: 'mu', flag_url: 'https://flagcdn.com/w40/mu.png', phone_code: '+230' },
  { name: 'Mauritania', code: 'mr', flag_url: 'https://flagcdn.com/w40/mr.png', phone_code: '+222' },
  { name: 'México', code: 'mx', flag_url: 'https://flagcdn.com/w40/mx.png', phone_code: '+52' },
  { name: 'Micronesia', code: 'fm', flag_url: 'https://flagcdn.com/w40/fm.png', phone_code: '+691' },
  { name: 'Moldavia', code: 'md', flag_url: 'https://flagcdn.com/w40/md.png', phone_code: '+373' },
  { name: 'Mónaco', code: 'mc', flag_url: 'https://flagcdn.com/w40/mc.png', phone_code: '+377' },
  { name: 'Mongolia', code: 'mn', flag_url: 'https://flagcdn.com/w40/mn.png', phone_code: '+976' },
  { name: 'Montenegro', code: 'me', flag_url: 'https://flagcdn.com/w40/me.png', phone_code: '+382' },
  { name: 'Mozambique', code: 'mz', flag_url: 'https://flagcdn.com/w40/mz.png', phone_code: '+258' },
  { name: 'Birmania', code: 'mm', flag_url: 'https://flagcdn.com/w40/mm.png', phone_code: '+95' },
  { name: 'Namibia', code: 'na', flag_url: 'https://flagcdn.com/w40/na.png', phone_code: '+264' },
  { name: 'Nauru', code: 'nr', flag_url: 'https://flagcdn.com/w40/nr.png', phone_code: '+674' },
  { name: 'Nepal', code: 'np', flag_url: 'https://flagcdn.com/w40/np.png', phone_code: '+977' },
  { name: 'Nicaragua', code: 'ni', flag_url: 'https://flagcdn.com/w40/ni.png', phone_code: '+505' },
  { name: 'Níger', code: 'ne', flag_url: 'https://flagcdn.com/w40/ne.png', phone_code: '+227' },
  { name: 'Nigeria', code: 'ng', flag_url: 'https://flagcdn.com/w40/ng.png', phone_code: '+234' },
  { name: 'Noruega', code: 'no', flag_url: 'https://flagcdn.com/w40/no.png', phone_code: '+47' },
  { name: 'Nueva Zelanda', code: 'nz', flag_url: 'https://flagcdn.com/w40/nz.png', phone_code: '+64' },
  { name: 'Omán', code: 'om', flag_url: 'https://flagcdn.com/w40/om.png', phone_code: '+968' },
  { name: 'Países Bajos', code: 'nl', flag_url: 'https://flagcdn.com/w40/nl.png', phone_code: '+31' },
  { name: 'Pakistán', code: 'pk', flag_url: 'https://flagcdn.com/w40/pk.png', phone_code: '+92' },
  { name: 'Palaos', code: 'pw', flag_url: 'https://flagcdn.com/w40/pw.png', phone_code: '+680' },
  { name: 'Panamá', code: 'pa', flag_url: 'https://flagcdn.com/w40/pa.png', phone_code: '+507' },
  { name: 'Papúa Nueva Guinea', code: 'pg', flag_url: 'https://flagcdn.com/w40/pg.png', phone_code: '+675' },
  { name: 'Paraguay', code: 'py', flag_url: 'https://flagcdn.com/w40/py.png', phone_code: '+595' },
  { name: 'Perú', code: 'pe', flag_url: 'https://flagcdn.com/w40/pe.png', phone_code: '+51' },
  { name: 'Polonia', code: 'pl', flag_url: 'https://flagcdn.com/w40/pl.png', phone_code: '+48' },
  { name: 'Portugal', code: 'pt', flag_url: 'https://flagcdn.com/w40/pt.png', phone_code: '+351' },
  { name: 'Reino Unido', code: 'gb', flag_url: 'https://flagcdn.com/w40/gb.png', phone_code: '+44' },
  { name: 'República Centroafricana', code: 'cf', flag_url: 'https://flagcdn.com/w40/cf.png', phone_code: '+236' },
  { name: 'República Checa', code: 'cz', flag_url: 'https://flagcdn.com/w40/cz.png', phone_code: '+420' },
  { name: 'República del Congo', code: 'cd', flag_url: 'https://flagcdn.com/w40/cd.png', phone_code: '+243' },
  { name: 'República Dominicana', code: 'do', flag_url: 'https://flagcdn.com/w40/do.png', phone_code: '+1809' },
  { name: 'Ruanda', code: 'rw', flag_url: 'https://flagcdn.com/w40/rw.png', phone_code: '+250' },
  { name: 'Rumania', code: 'ro', flag_url: 'https://flagcdn.com/w40/ro.png', phone_code: '+40' },
  { name: 'Rusia', code: 'ru', flag_url: 'https://flagcdn.com/w40/ru.png', phone_code: '+7' },
  { name: 'Samoa', code: 'ws', flag_url: 'https://flagcdn.com/w40/ws.png', phone_code: '+685' },
  { name: 'San Cristóbal y Nieves', code: 'kn', flag_url: 'https://flagcdn.com/w40/kn.png', phone_code: '+1869' },
  { name: 'San Marino', code: 'sm', flag_url: 'https://flagcdn.com/w40/sm.png', phone_code: '+378' },
  { name: 'San Vicente y las Granadinas', code: 'vc', flag_url: 'https://flagcdn.com/w40/vc.png', phone_code: '+1784' },
  { name: 'Santa Lucía', code: 'lc', flag_url: 'https://flagcdn.com/w40/lc.png', phone_code: '+1758' },
  { name: 'Santo Tomé y Príncipe', code: 'st', flag_url: 'https://flagcdn.com/w40/st.png', phone_code: '+239' },
  { name: 'Senegal', code: 'sn', flag_url: 'https://flagcdn.com/w40/sn.png', phone_code: '+221' },
  { name: 'Serbia', code: 'rs', flag_url: 'https://flagcdn.com/w40/rs.png', phone_code: '+381' },
  { name: 'Seychelles', code: 'sc', flag_url: 'https://flagcdn.com/w40/sc.png', phone_code: '+248' },
  { name: 'Sierra Leona', code: 'sl', flag_url: 'https://flagcdn.com/w40/sl.png', phone_code: '+232' },
  { name: 'Singapur', code: 'sg', flag_url: 'https://flagcdn.com/w40/sg.png', phone_code: '+65' },
  { name: 'Siria', code: 'sy', flag_url: 'https://flagcdn.com/w40/sy.png', phone_code: '+963' },
  { name: 'Somalia', code: 'so', flag_url: 'https://flagcdn.com/w40/so.png', phone_code: '+252' },
  { name: 'Sri Lanka', code: 'lk', flag_url: 'https://flagcdn.com/w40/lk.png', phone_code: '+94' },
  { name: 'Suazilandia', code: 'sz', flag_url: 'https://flagcdn.com/w40/sz.png', phone_code: '+268' },
  { name: 'Sudáfrica', code: 'za', flag_url: 'https://flagcdn.com/w40/za.png', phone_code: '+27' },
  { name: 'Sudán', code: 'sd', flag_url: 'https://flagcdn.com/w40/sd.png', phone_code: '+249' },
  { name: 'Sudán del Sur', code: 'ss', flag_url: 'https://flagcdn.com/w40/ss.png', phone_code: '+211' },
  { name: 'Suecia', code: 'se', flag_url: 'https://flagcdn.com/w40/se.png', phone_code: '+46' },
  { name: 'Suiza', code: 'ch', flag_url: 'https://flagcdn.com/w40/ch.png', phone_code: '+41' },
  { name: 'Surinam', code: 'sr', flag_url: 'https://flagcdn.com/w40/sr.png', phone_code: '+597' },
  { name: 'Tailandia', code: 'th', flag_url: 'https://flagcdn.com/w40/th.png', phone_code: '+66' },
  { name: 'Tanzania', code: 'tz', flag_url: 'https://flagcdn.com/w40/tz.png', phone_code: '+255' },
  { name: 'Tayikistán', code: 'tj', flag_url: 'https://flagcdn.com/w40/tj.png', phone_code: '+992' },
  { name: 'Timor Oriental', code: 'tl', flag_url: 'https://flagcdn.com/w40/tl.png', phone_code: '+670' },
  { name: 'Togo', code: 'tg', flag_url: 'https://flagcdn.com/w40/tg.png', phone_code: '+228' },
  { name: 'Tonga', code: 'to', flag_url: 'https://flagcdn.com/w40/to.png', phone_code: '+676' },
  { name: 'Trinidad y Tobago', code: 'tt', flag_url: 'https://flagcdn.com/w40/tt.png', phone_code: '+1868' },
  { name: 'Túnez', code: 'tn', flag_url: 'https://flagcdn.com/w40/tn.png', phone_code: '+216' },
  { name: 'Turkmenistán', code: 'tm', flag_url: 'https://flagcdn.com/w40/tm.png', phone_code: '+993' },
  { name: 'Turquía', code: 'tr', flag_url: 'https://flagcdn.com/w40/tr.png', phone_code: '+90' },
  { name: 'Tuvalu', code: 'tv', flag_url: 'https://flagcdn.com/w40/tv.png', phone_code: '+688' },
  { name: 'Ucrania', code: 'ua', flag_url: 'https://flagcdn.com/w40/ua.png', phone_code: '+380' },
  { name: 'Uganda', code: 'ug', flag_url: 'https://flagcdn.com/w40/ug.png', phone_code: '+256' },
  { name: 'Uruguay', code: 'uy', flag_url: 'https://flagcdn.com/w40/uy.png', phone_code: '+598' },
  { name: 'Uzbekistán', code: 'uz', flag_url: 'https://flagcdn.com/w40/uz.png', phone_code: '+998' },
  { name: 'Vanuatu', code: 'vu', flag_url: 'https://flagcdn.com/w40/vu.png', phone_code: '+678' },
  { name: 'Venezuela', code: 've', flag_url: 'https://flagcdn.com/w40/ve.png', phone_code: '+58' },
  { name: 'Vietnam', code: 'vn', flag_url: 'https://flagcdn.com/w40/vn.png', phone_code: '+84' },
  { name: 'Yemen', code: 'ye', flag_url: 'https://flagcdn.com/w40/ye.png', phone_code: '+967' },
  { name: 'Yibuti', code: 'dj', flag_url: 'https://flagcdn.com/w40/dj.png', phone_code: '+253' },
  { name: 'Zambia', code: 'zm', flag_url: 'https://flagcdn.com/w40/zm.png', phone_code: '+260' },
  { name: 'Zimbabue', code: 'zw', flag_url: 'https://flagcdn.com/w40/zw.png', phone_code: '+263' }
]

export const useCountries = () => {
  const [countries] = useState<Country[]>(allCountries)
  const [loading] = useState(false)
  const [error] = useState<string | null>(null)

  return { countries, loading, error }
}